version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: quarterly

  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 3
    groups:
      cargo:
        patterns:
          - "*"
    schedule:
      interval: quarterly
